### ISSUE TITLE
Login success but accesstoken null

### ISSUE THREAD

**Issue by lqmminh** [tiendung01023/zalo_flutter#8]
{isSuccess: true, data: {refreshToken: null, expriedTime: null, accessToken: null}}
Hi anh, nhờ anh check hộ phần này

**Comment by lqmminh** [comment]
lỗi này xuất hiện trên ios

**Comment by huantd0111** [comment]
@lqmminh bạn đã fix được case này chưa b?

**Comment by lqmminh** [comment]
@huantd0111 chưa bạn ơi

**Comment by lqmminh** [comment]
@tiendung01023

**Comment by anhphongit** [comment]
Sau khi đọc code thì em thấy root cause nằm ở chỗ [này](https://github.com/tiendung01023/zalo_flutter/commit/a1544d9cc4997185ed2e74f10381539656c0ff05#diff-8c583387d1c02066dcf97c2825b4e4c5b37d5ca01895eecb19cab79ebbe76957):

`try {
      if (rs != null && rs['data'] != null && rs['data'] is Map<dynamic, dynamic>) {
        final Map<dynamic, dynamic>? data = rs['data'] as Map<dynamic, dynamic>?;
        data?['accessToken'] = data['access_token'];
        data?['refreshToken'] = data['refresh_token'];
        data?['expriedTime'] = data['expires_in'];
        data?.remove('access_token');
        data?.remove('refresh_token');
        data?.remove('expires_in');
      }
    // ignore: empty_catches
    } catch (e) {}`

Cơ bản là rs['data'] do ZaloSDK trả về khác nhau giữa Android và iOS, cụ thể trên iOS đang trả về 'accessToken', 'refreshToken', 'expriedTime'; còn Android đang trả về 'access_token', 'refresh_token', 'expires_in'; nên dẫn đến issue trên iOS.

@tiendung01023

**Comment by tiendung01023** [comment]
@anhphongit Dạ đúng rồi anh, vấn đề này hồi trước em khắc phục cho iOS để trả data cho đồng bộ, mà chưa hiểu vì sao data gần đây bị thay đổi nên code bị chạy sai, tạm thời mình sẽ trả data gốc về cho mọi người để mọi người sử dụng đỡ trước.
